-- Phase 3: Supabase Optimization & Financial Edge Cases

-- 1. Create Payment Table
CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospital(id),
    bill_id BIGINT NOT NULL REFERENCES bill(id),
    amount_paid DECIMAL(12, 2) NOT NULL,
    payment_mode VARCHAR(50) NOT NULL,
    transaction_reference VARCHAR(255) NOT NULL,
    payment_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remarks TEXT
);

-- 2. Create PharmacyRecall Table
CREATE TABLE IF NOT EXISTS pharmacy_recall (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospital(id),
    medicine_name VARCHAR(255) NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    recall_reason TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    recalled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Add High-Performance Indexes for Multi-Tenant Queries
CREATE INDEX IF NOT EXISTS idx_payment_hospital_id ON payment(hospital_id);
CREATE INDEX IF NOT EXISTS idx_payment_bill_id ON payment(bill_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_recall_hospital_id ON pharmacy_recall(hospital_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_recall_lookup ON pharmacy_recall(hospital_id, medicine_name, batch_number);

-- Ensure common queries have compound indexes
CREATE INDEX IF NOT EXISTS idx_appointment_doctor_date ON appointment(doctor_id, appointment_date, status);
CREATE INDEX IF NOT EXISTS idx_dispensation_hospital_status ON dispensation_record(hospital_id, billing_status);
CREATE INDEX IF NOT EXISTS idx_bill_hospital_patient ON bill(hospital_id, patient_id, payment_status);

-- 4. Enable Row-Level Security (RLS) Foundations
-- (Future-proofing for Supabase direct auth access)
ALTER TABLE hospital ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient ENABLE ROW LEVEL SECURITY;
ALTER TABLE doctor ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointment ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment ENABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_recall ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicine_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispensation_record ENABLE ROW LEVEL SECURITY;

-- Provide a default policy allowing all operations for the service role (PostgreSQL user)
-- For now, the application connects as a superuser/owner, so RLS doesn't block it.
-- These policies are just a foundational layer for when direct client-side Supabase connections are made.
CREATE POLICY "Enable all for postgres admin" ON hospital USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON app_user USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON patient USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON doctor USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON appointment USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON bill USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON payment USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON pharmacy_recall USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON medicine_stock USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for postgres admin" ON dispensation_record USING (true) WITH CHECK (true);
